name: Ping Supabase

on:
  schedule:
    # Runs on the 1st and 15th of every month
    - cron: '0 0 * * 0'

jobs:
  ping-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase URL
        run: |
          curl -X HEAD -I \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          "${{ secrets.SUPABASE_URL }}"
